#!/usr/bin/env python3
"""Generate deeply nested Luau expressions for recursion-depth stress tests.

Each generated program evaluates a binary operator tree of configurable
depth. The default operator is `..` (string concatenation), but arithmetic
operators can be used instead.

Usage:
    python nested_expr_generator.py --depth 200 --op ".." --out out.luau
"""

import argparse
import sys
from pathlib import Path


def generate(depth: int, op: str) -> str:
    """Return a Luau program containing one deeply nested expression."""
    if depth < 1:
        raise ValueError("depth must be >= 1")

    if op == "..":
        leaf = '"a"'
    else:
        leaf = "1"

    expr = leaf
    for _ in range(depth - 1):
        expr = f"({leaf} {op} {expr})"

    return (
        "-- generated by nested_expr_generator.py\n"
        f"-- depth = {depth}, operator = {op!r}\n"
        f"local x = {expr}\n"
        "return x\n"
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--depth", type=int, default=100,
                        help="number of leaves in the nested expression")
    parser.add_argument("--op", default="..",
                        choices=["..", "+", "*", "^", "and", "or"],
                        help="binary operator to chain")
    parser.add_argument("--out", default=None,
                        help="output file; defaults to stdout")
    args = parser.parse_args(argv)

    source = generate(args.depth, args.op)
    if args.out:
        Path(args.out).write_text(source, encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
