#!/usr/bin/env python3
"""Generate random but syntactically valid Luau programs.

This is a tiny recursive generator that emits a random sequence of
statements and expressions guaranteed to parse. It is intentionally simple;
use it to produce a large volume of smoke-test inputs.

Usage:
    python random_valid_ast_generator.py --count 100 --out-dir out/
"""

import argparse
import random
import sys
from pathlib import Path

IDENTIFIERS = ["a", "b", "c", "x", "y", "z", "foo", "bar", "value", "total"]


def expr(rng: random.Random, depth: int = 0) -> str:
    if depth > 4:
        return str(rng.randint(0, 100))
    kind = rng.choice(["int", "str", "ident", "call", "binop", "table", "paren"])
    if kind == "int":
        return str(rng.randint(0, 1000))
    if kind == "str":
        return '"' + rng.choice(["hello", "world", "abc", "x"]) + '"'
    if kind == "ident":
        return rng.choice(IDENTIFIERS)
    if kind == "call":
        name = rng.choice(["tostring", "tonumber", "type", "select"])
        return f"{name}({expr(rng, depth + 1)})"
    if kind == "binop":
        op = rng.choice(["+", "-", "*", ".."])
        return f"({expr(rng, depth + 1)} {op} {expr(rng, depth + 1)})"
    if kind == "table":
        items = ", ".join(expr(rng, depth + 1) for _ in range(rng.randint(0, 3)))
        return "{ " + items + " }"
    return f"({expr(rng, depth + 1)})"


def statement(rng: random.Random, depth: int = 0) -> str:
    kind = rng.choice(["local", "assign", "if", "for", "return"])
    if kind == "local":
        name = rng.choice(IDENTIFIERS)
        return f"local {name} = {expr(rng, depth)}"
    if kind == "assign":
        name = rng.choice(IDENTIFIERS)
        return f"{name} = {expr(rng, depth)}"
    if kind == "if":
        return (
            f"if {expr(rng, depth)} then\n"
            f"    {statement(rng, depth + 1)}\n"
            "end"
        )
    if kind == "for":
        name = rng.choice(IDENTIFIERS)
        return (
            f"for {name} = 1, 3 do\n"
            f"    {statement(rng, depth + 1)}\n"
            "end"
        )
    return f"return {expr(rng, depth)}"


def generate_program(rng: random.Random, n_statements: int = 10) -> str:
    body = "\n".join(statement(rng) for _ in range(n_statements))
    header = "-- generated by random_valid_ast_generator.py\n"
    return header + body + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--statements", type=int, default=10)
    parser.add_argument("--out-dir", default=".")
    args = parser.parse_args(argv)

    rng = random.Random(args.seed)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for i in range(args.count):
        path = out / f"random-{i:04d}.luau"
        path.write_text(generate_program(rng, args.statements), encoding="utf-8")
    print(f"wrote {args.count} files to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
